"""add next_retry_at to posts

Revision ID: d953dc726d73
Revises: 659f7adc27d7
Create Date: 2026-02-27 21:02:03.848099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd953dc726d73'
down_revision: Union[str, None] = '659f7adc27d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_posts_failed_retry', 'posts', ['status', 'next_retry_at'], unique=False, postgresql_where=sa.text("status = 'failed'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_failed_retry', table_name='posts', postgresql_where=sa.text("status = 'failed'"))
    op.drop_column('posts', 'next_retry_at')
    # ### end Alembic commands ###
